### ISSUE TITLE
[BUG]Cnosdb cannot connect through the jdbc driver

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1324]
### Describe the bug

Cnosdb cannot connect through the jdbc driver!
cnosdb version : a848ccb7eed15486d97d1e0537d358d8ce8fa034

### To Reproduce

step as office web site:
https://docs.cnosdb.com/zh/v2.3/reference/connector/arrow_flight_sql.html#%E4%B8%8D%E5%90%8C%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%9A%84%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F

### Additional context

```log
[root@cicd_ujv23 jdbc]# env _JAVA_OPTIONS="--add-opens=java.base/java.nio=ALL-UNNAMED" java -jar target/jdbc-1.0-SNAPSHOT.jar 
Picked up _JAVA_OPTIONS: --add-opens=java.base/java.nio=ALL-UNNAMED
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cfjd.org.apache.calcite.avatica.com.google.protobuf.UnsafeUtil (file:/data/ce/code/test_jdbc/jdbc/jdbc/target/lib/flight-sql-jdbc-driver-10.0.1.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of cfjd.org.apache.calcite.avatica.com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.RuntimeException: java.sql.SQLException: Error while executing SQL "SELECT 1, 2, 3;": 
	at com.cnosdb.Main.main(Main.java:34)
Caused by: java.sql.SQLException: Error while executing SQL "SELECT 1, 2, 3;": 
	at cfjd.org.apache.calcite.avatica.Helper.createException(Helper.java:56)
	at cfjd.org.apache.calcite.avatica.Helper.createException(Helper.java:41)
	at cfjd.org.apache.calcite.avatica.AvaticaStatement.executeInternal(AvaticaStatement.java:163)
	at cfjd.org.apache.calcite.avatica.AvaticaStatement.executeQuery(AvaticaStatement.java:227)
	at com.cnosdb.Main.main(Main.java:25)
Caused by: cfjd.org.apache.arrow.flight.FlightRuntimeException: CANCELLED: 
	at cfjd.org.apache.arrow.flight.CallStatus.toRuntimeException(CallStatus.java:131)
	at cfjd.org.apache.arrow.flight.sql.FlightSqlClient$PreparedStatement.executeUpdate(FlightSqlClient.java:1061)
	at org.apache.arrow.driver.jdbc.client.ArrowFlightSqlClientHandler$1.executeUpdate(ArrowFlightSqlClientHandler.java:179)
	at org.apache.arrow.driver.jdbc.ArrowFlightMetaImpl.prepareAndExecute(ArrowFlightMetaImpl.java:166)
	at cfjd.org.apache.calcite.avatica.AvaticaConnection.prepareAndExecuteInternal(AvaticaConnection.java:675)
	at cfjd.org.apache.calcite.avatica.AvaticaStatement.executeInternal(AvaticaStatement.java:156)
	... 2 more
Caused by: java.util.concurrent.ExecutionException: cfjd.org.apache.arrow.flight.FlightRuntimeException: UNIMPLEMENTED: do_put_prepared_statement_update not implemented
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2070)
	at cfjd.org.apache.arrow.flight.SyncPutListener.unwrap(SyncPutListener.java:50)
	at cfjd.org.apache.arrow.flight.SyncPutListener.read(SyncPutListener.java:64)
	at cfjd.org.apache.arrow.flight.sql.FlightSqlClient$PreparedStatement.executeUpdate(FlightSqlClient.java:1054)
	... 6 more
Caused by: cfjd.org.apache.arrow.flight.FlightRuntimeException: UNIMPLEMENTED: do_put_prepared_statement_update not implemented
	at cfjd.org.apache.arrow.flight.CallStatus.toRuntimeException(CallStatus.java:131)
	at cfjd.org.apache.arrow.flight.grpc.StatusUtils.fromGrpcRuntimeException(StatusUtils.java:164)
	at cfjd.org.apache.arrow.flight.grpc.StatusUtils.fromThrowable(StatusUtils.java:185)
	at cfjd.org.apache.arrow.flight.FlightClient$SetStreamObserver.onError(FlightClient.java:445)
	at cfjd.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at cfjd.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at cfjd.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at cfjd.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at cfjd.org.apache.arrow.flight.grpc.ClientInterceptorAdapter$FlightClientCallListener.onClose(ClientInterceptorAdapter.java:117)
	at cfjd.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
	at cfjd.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at cfjd.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
	at cfjd.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at cfjd.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at cfjd.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by Benxiaohai001** [comment]
verision: cnosdb 2.3.1, revision 6a0e5f4467d1fdc6c1038958cd712d35fc8bec53
the bug is fixed,so close the issue;
```log
[root@cicd_ujv23 jdbc]# _JAVA_OPTIONS="--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED" mvn exec:java -Dexec.mainClass="com.cnosdb.Main"
Picked up _JAVA_OPTIONS: --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< com.cnosdb:jdbc >---------------------------
[INFO] Building jdbc 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:3.1.0:java (default-cli) @ jdbc ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
1 2 3[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.212 s
[INFO] Finished at: 2023-07-07T15:24:32+08:00
[INFO] ------------------------------------------------------------------------
```
