### ISSUE TITLE
Panic on writeDatabaseInfo

### ISSUE THREAD

**Issue by bartliu827** [cnosdb/cnosdb#293]
panic: interface conversion: interface { Data() meta.Data; Database(string) *meta.DatabaseInfo; MarshalBinary() ([]uint8, error); SetData(*meta.Data) error } is *meta.RemoteClient, not *meta.Client

goroutine 203 [running]:
github.com/cnosdb/cnosdb/server/snapshotter.(*Service).writeDatabaseInfo(0x140001342d0, {0x10135d268?, 0x14000278150}, {0x0?, 0x0?})
	/Users/adminliu/github.com/cnosdb/cnosdb/server/snapshotter/service.go:304 +0x4dc
github.com/cnosdb/cnosdb/server/snapshotter.(*Service).handleConn(0x140001342d0, {0x10135d268?, 0x14000278150})
	/Users/adminliu/github.com/cnosdb/cnosdb/server/snapshotter/service.go:149 +0x15c
github.com/cnosdb/cnosdb/server/snapshotter.(*Service).serve.func1({0x10135d268?, 0x14000278150?})
	/Users/adminliu/github.com/cnosdb/cnosdb/server/snapshotter/service.go:111 +0xa0
created by github.com/cnosdb/cnosdb/server/snapshotter.(*Service).serve
	/Users/adminliu/github.com/cnosdb/cnosdb/server/snapshotter/service.go:108 +0x27c

**Comment by bartliu827** [comment]
//dbs = s.MetaClient.(*meta.Client).Databases()
dbs = s.MetaClient.Data().Databases
