### ISSUE TITLE
[Compile] compile error

### ISSUE THREAD

**Issue by fansehep** [cnosdb/cnosdb#812]
**Describe the bug**
the latest branch compile error in my machine.
```bash
Arch Linux 6.1.1 x86_64
rustc version 1.64.0
cargo version: 1.64.0
```
cargo ouput:

```bash
Caused by:
  process didn't exit successfully: `/home/fanr/Github/cnosdb/target/debug/build/protos-98787f2df9789b3c/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Failed to generate file 'models.rs' by flatc(path: 'flatc'): Os { code: 2, kind: NotFound, message: "No such file or directory" }.', common/protos/build.rs:123:21
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
     2: build_script_build::main::{{closure}}
               at ./build.rs:123:21
     3: core::result::Result<T,E>::unwrap_or_else
               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1493:23
     4: build_script_build::main
               at ./build.rs:111:26
     5: core::ops::function::FnOnce::call_once
               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
```

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by Subsegment** [comment]
docs/quick-start.md

flatbuffer is required

**Comment by fansehep** [comment]
> docs/quick-start.md
> 
> flatbuffer is required

ok, fix it. thanks
